/*p1*/
select CITY,STATE from STATION;
/*p2*/
SELECT DISTINCT CITY 
FROM STATION 
WHERE MOD(ID,2)=0 
ORDER BY CITY ASC; 
/*p3*/
SELECT SUM(POPULATION)
FROM CITY
WHERE DISTRICT = 'California';
/*p4*/
SELECT COUNT(POPULATION)
FROM CITY
WHERE POPULATION > 100000;
/*p5*/
SELECT CASE
WHEN A + B <= C OR A + C <= B OR B + C <= A THEN 'Not A Triangle'
WHEN A = B AND B = C THEN 'Equilateral'
WHEN A = B OR B = C OR A = C THEN 'Isosceles'
ELSE 'Scalene'
END
FROM TRIANGLES;
